"""Auto-generated Korean-English POE translations"""

# Total: 815 translations

POE_TRANSLATIONS_FULL = {
    "가마 관리인 렌카르": "Renkarr%2C The Kiln Keeper",
    "가마솥의 마녀": "Witch of the Cauldron",
    "가뭄에 미친 로아": "Drought-Maddened Rhoa",
    "가속": "Haste",
    "가시": "Thorn",
    "가시망치 멜루르": "Melur Thornmaul",
    "감금의 시체 불덩이": "Volatile Dead of Confinement",
    "강철 관통": "Lancing Steel",
    "강철 분할": "Splitting Steel",
    "강철 영혼": "The Steel Soul",
    "강철 파편": "Shattering Steel",
    "강철피부": "Steelskin",
    "강타의 좀비 소환": "Raise Zombie of Slamming",
    "강탈자": "The Reaver",
    "강화된 희미한 기억 결합된 지도": "Augmented Distant Memory",
    "거대한 고대인 토어": "Tore%2C Towering Ancient",
    "거대한 덩굴의 여왕": "Queen of the Great Tangle",
    "거룩한 껍데기": "The Hallowed Husk",
    "거룩한 대지 공동묘지 지도": "Hallowed Ground",
    "거미증": "Arachnoxia",
    "거울 화살": "Mirror Arrow",
    "거인 처형자 오테사": "Otesha%2C the Giantslayer",
    "거짓 희망의 방적꾼": "Spinner of False Hope",
    "검은 근위대 복수자": "Blackguard Avenger",
    "검은 근위대 폭풍": "Blackguard Tempest",
    "검의 대가": "Master of the Blade",
    "검의 폭풍": "Swordstorm",
    "검투사의 타쇄자": "Crusher of Gladiators",
    "검투사의 파괴자": "Shredder of Gladiators",
    "겁쟁이의 시험 저주받은 지하실 지도": "The Cowards Trial",
    "겨울 보주": "Winter Orb",
    "겨울송곳니": "Winterfang",
    "겨울의 낙인": "Wintertide Brand",
    "겨울의 눈": "Eye of Winter",
    "겨울의 조각": "Fragment of Winter",
    "격노 소용돌이": "Rage Vortex",
    "격노의 유령 소환": "Summon Raging Spirit",
    "격노의 회전베기": "Cleave of Rage",
    "격동하는 원소의 회오리": "Tornado of Elemental Turbulence",
    "격려의 면죄": "Absolution of Inspiring",
    "격려의 지배의 맹타": "Dominating Blow of Inspiring",
    "격렬함의 충격장": "Galvanic Field of Intensity",
    "격분": "Frenzy",
    "격화의 덩굴 번개": "Lightning Tendrils of Escalation",
    "결빙의 얼음 폭발": "Ice Nova of Deep Freeze",
    "결의": "Determination",
    "경계 타격": "Vigilant Strike",
    "계시의 정화의 불길": "Purifying Flame of Revelations",
    "고대의 조각가": "Ancient Sculptor",
    "고드름 지뢰": "Icicle Mine",
    "고르곤": "The Gorgon",
    "고사시키는 걸음": "Withering Step",
    "고사의 맹독성 비": "Toxic Rain of Withering",
    "고위 강령술사 시식": "Xixic%2C High Necromancer",
    "고위 석마술사": "High Lithomancer",
    "고위 템플러": "The High Templar",
    "고통받는 요녀": "Tormented Temptress",
    "고통의 이교도 주교": "Pagan Bishop of Agony",
    "고통의 전령": "Herald of Agony",
    "곰 덫": "Bear Trap",
    "공격적인 적수": "Invasive Adversaries",
    "공전의 구형 번개": "Ball Lightning of Orbiting",
    "공포의 깃발": "Dread Banner",
    "공허 구체": "Void Sphere",
    "공허의 이형": "Void Anomaly",
    "과부하된 회로": "Overloaded Circuits",
    "과부하의 번개 첨탑 덫": "Lightning Spire Trap of Overloading",
    "관통상": "Puncture",
    "관통의 얼음 화살": "Ice Shot of Penetration",
    "광분에 찬 화염 마녀": "Fire and Fury",
    "광야의 소각": "Incinerate of Expanse",
    "광폭": "Berserk",
    "광폭화의 격노 소용돌이": "Rage Vortex of Berserking",
    "교두보 선구자 지도": "The Beachhead",
    "구름폭발의 회오리 사격": "Tornado Shot of Cloudburst",
    "구불거림의 화산 균열": "Volcanic Fissure of Snaking",
    "구체화의 환영 무기 투척": "Spectral Throw of Materialising",
    "구형 번개": "Ball Lightning",
    "군단 처형자 앰브리우스": "Ambrius%2C Legion Slayer",
    "군단의 돌 골렘 소환": "Summon Stone Golem of Hordes",
    "군단의 번개 골렘 소환": "Summon Lightning Golem of Hordes",
    "군단의 부패 골렘 소환": "Summon Carrion Golem of Hordes",
    "군단의 얼음 골렘 소환": "Summon Ice Golem of Hordes",
    "군단의 카오스 골렘 소환": "Summon Chaos Golem of Hordes",
    "군단의 화염 골렘 소환": "Summon Flame Golem of Hordes",
    "군집의 역학 폭발": "Kinetic Blast of Clustering",
    "굴절의 약탈": "Reave of Refraction",
    "궁수의 해골 소환": "Summon Skeletons of Archers",
    "권능 착취": "Power Siphon",
    "권능의 점멸 타격": "Flicker Strike of Power",
    "권능의 한파": "Cold Snap of Power",
    "귀를 찢는 자 모그란츠": "Morgrants%2C The Deafening",
    "귀환의 화염 질주": "Flame Dash of Return",
    "규모의 폭발 덫": "Explosive Trap of Magnitude",
    "규탄의 파멸": "Bane of Condemnation",
    "균열의 빙하 폭포": "Glacial Cascade of the Fissure",
    "그의 불타는 뜻": "His Burning Message",
    "극단의 사나운 타격": "Wild Strike of Extremes",
    "극악무도의 격노의 유령 소환": "Summon Raging Spirit of Enormity",
    "글라스": "Glace",
    "금단의 맛 석영 플라스크": "Forbidden Taste",
    "금단의 의식": "Forbidden Rite",
    "기만자 로칸": "Lokan%2C The Deceiver",
    "기만적인 신": "The Deceitful God",
    "기세의 이중 타격": "Double Strike of Momentum",
    "기행의 덩굴 번개": "Lightning Tendrils of Eccentricity",
    "꼬챙이의 곰 덫": "Bear Trap of Skewers",
    "꿈의 감염자": "Infector of Dreams",
    "꿈틀거리는 단지 거룩한 하이브리드 플라스크": "The Writhing Jar",
    "꿰뚫기의 이중 타격": "Double Strike of Impaling",
    "꿰뚫기의 칼날비": "Bladefall of Impaling",
    "끊어진 원의 영액 철 플라스크": "Elixir of the Unbroken Circle",
    "끌로 새긴 완벽": "Chiselled Perfection",
    "끓어오름의 시체 불덩이": "Volatile Dead of Seething",
    "끔찍한 자 샤브론": "Shavronne the Sickening",
    "끝나지 않는 낮 헬리알": "Helial%2C the Day Unending",
    "끝없는 밤 셀레니아": "Selenia%2C the Endless Night",
    "나선의 영혼 분리": "Soulrend of the Spiral",
    "낙인 소환": "Brand Recall",
    "낙하하는 괴물": "It That Fell",
    "낙하하는 수정": "Falling Crystals",
    "난사의 칼날 폭격": "Blade Blast of Unloading",
    "날개 달린 죽음": "The Winged Death",
    "낫의 칼날 소용돌이": "Blade Vortex of the Scythe",
    "낫질": "Reap",
    "낫질의 영혼 분리": "Soulrend of Reaping",
    "내장 적출": "Eviscerate",
    "넘치는 성배 유황 플라스크": "The Overflowing Chalice",
    "노여움의 신성한 화염 토템": "Holy Flame Totem of Ire",
    "높은 지도 등급 확률": "Higher Map Tier Chance",
    "뇌동의 연쇄 번개": "Arc of Oscillating",
    "뇌우": "Thunderstorm",
    "눈부리 프리티": "Preethi%2C Eye-Pecker",
    "늘어나는 속성": "Mounting Modifiers",
    "다모이 투이": "Damoi Tui",
    "다시 쓰인 희미한 기억 결합된 지도": "Rewritten Distant Memory",
    "다정한 포옹": "Tender Embrace",
    "단검 폭파의 칼날 폭격": "Blade Blast of Dagger Detonation",
    "단련": "Discipline",
    "단조의 화신": "Avatar of the Forge",
    "대검의 칼날 덫": "Blade Trap of Greatswords",
    "대눈사태": "The Great Avalanche",
    "대담한 과업": "Bold Undertakings",
    "대마법사의 권능 착취": "Power Siphon of the Archmage",
    "대장장이": "The Blacksmith",
    "대재앙의 지층 강타": "Tectonic Slam of Cataclysm",
    "대지 강타": "Ground Slam",
    "대지 분쇄의 산산조각": "Sunder of Earthbreaking",
    "덧없음의 겨울의 눈": "Eye of Winter of Transience",
    "덧없음의 망령 소환": "Raise Spectre of Transience",
    "덩굴 번개": "Lightning Tendrils",
    "도관의 폭풍우": "Storm Rain of the Conduit",
    "도륙의 천상의 단도": "Ethereal Knives of the Massacre",
    "도리아니의 기계실 미로 지도": "Doryanis Machinarium",
    "도살의 피부 찢기": "Lacerate of Butchering",
    "도약 강타": "Leap Slam",
    "도이드리의 묘약 대용량 마나 플라스크": "Doedres Elixir",
    "도이드리의 악몽": "Nightmare of Doedre",
    "도전자 푸루나": "Puruna%2C the Challenger",
    "독성 운반자": "Plague Bearer",
    "독성 혼합물": "Poisonous Concoction",
    "독액 선회": "Venom Gyre",
    "독의 부식성 화살": "Caustic Arrow of Poison",
    "돌 골렘 소환": "Summon Stone Golem",
    "동결 파동": "Freezing Pulse",
    "동상": "Frostbite",
    "동족 학살자 라마": "Rama%2C The Kinslayer",
    "되돌아온 자 머베일": "Merveil%2C the Returned",
    "두려움의 추기경": "The Cardinal of Fear",
    "뒤바뀐 희미한 기억 결합된 지도": "Altered Distant Memory",
    "뒤틀린 섬터": "Sumter the Twisted",
    "뒤틀린 희미한 기억 결합된 지도": "Twisted Distant Memory",
    "들이꽂는 관통상": "Puncture of Shanking",
    "땅 분쇄의 도약 강타": "Leap Slam of Groundbreaking",
    "땅을 태우는 메포드": "Mephod%2C the Earth Scorcher",
    "라비앙가의 혼백 모조품 축성된 마나 플라스크": "Replica Laviangas Spirit",
    "라비앙가의 혼백 축성된 마나 플라스크": "Laviangas Spirit",
    "루미의 혼합물 모조품 화강암 플라스크": "Replica Rumis Concoction",
    "루미의 혼합물 화강암 플라스크": "Rumis Concoction",
    "루비 플라스크": "Ruby Flask",
    "루시 "부패모" 로스": "Lussi %22Rotmother%22 Roth",
    "리안트라": "Liantra",
    "리키아의 악몽": "Nightmare of Lycia",
    "마나": "Mana",
    "마나 결속": "Manabond",
    "마법사의 해골 소환": "Summon Skeletons of Mages",
    "마엘스트롬의 카오스 골렘 소환": "Summon Chaos Golem of the Maelstr%C3%B6m",
    "마오 쿤 바닷가 지도": "Mao Kun",
    "말라붙은 황제": "The Brittle Emperor",
    "말리가로의 악몽": "Nightmare of Maligaro",
    "망령 소환": "Raise Spectre",
    "망치 헤파이우스": "Hephaeus%2C The Hammer",
    "매복": "Ambush",
    "맹공의 격분": "Frenzy of Onslaught",
    "맹독 타격": "Viper Strike",
    "맹독성 비": "Toxic Rain",
    "맹렬한 포격": "Blazing Salvo",
    "맹신자의 서약": "Zealots Oath",
    "먼지로 돌아가라": "Return to Dust",
    "메가이라": "Megaera",
    "면죄": "Absolution",
    "명상": "Clarity",
    "명인의 전당 산책로 지도": "Hall of Grandmasters",
    "모독": "Desecrate",
    "모독자 도이드리": "Doedre the Defiler",
    "몰락자 칼리아": "Kalria%2C The Fallen",
    "몰락한 여왕": "The Fallen Queen",
    "몰려오는 마그마": "Rolling Magma",
    "무기 기동": "Animate Weapon",
    "무리의 우두머리 솔루스": "Solus%2C Pack Alpha",
    "무상의 얼음 덫": "Ice Trap of Hollowness",
    "무쌍의 베시더": "Vessider%2C The Unrivaled",
    "무한한 표류의 공포": "Terror of the Infinite Drifts",
    "묵직한 타격": "Heavy Strike",
    "물의 구체": "Hydrosphere",
    "미끼 토템": "Decoy Totem",
    "미노타우로스의 수호자": "Guardian of the Minotaur",
    "미친 남작 페스퀸": "Pesquin%2C the Mad Baron",
    "민첩함의 화염파": "Flameblast of Celerity",
    "밀렵꾼의 징표": "Poachers Mark",
    "바알 가속": "Vaal Haste",
    "바알 권능 착취": "Vaal Power Siphon",
    "바알 균열": "Vaal Breach",
    "바알 낫질": "Vaal Reap",
    "바알 단련": "Vaal Discipline",
    "바알 대지 강타": "Vaal Ground Slam",
    "바알 독액 선회": "Vaal Venom Gyre",
    "바알 면죄": "Vaal Absolution",
    "바알 명상": "Vaal Clarity",
    "바알 무기 기동": "Vaal Animate Weapon",
    "바알 번개 덫": "Vaal Lightning Trap",
    "바알 번개 차원 이동": "Vaal Lightning Warp",
    "바알 번개 타격": "Vaal Lightning Strike",
    "바알 번개 화살": "Vaal Lightning Arrow",
    "바알 번개의 부정함": "Vaal Impurity of Lightning",
    "바알 부식성 화살": "Vaal Caustic Arrow",
    "바알 불멸의 외침": "Vaal Immortal Call",
    "바알 불의 부정함": "Vaal Impurity of Fire",
    "바알 불타는 화살": "Vaal Burning Arrow",
    "바알 빙하 망치": "Vaal Glacial Hammer",
    "바알 사원 지도": "Vaal Temple Map",
    "바알 선대의 대전사": "Vaal Ancestral Warchief",
    "바알 시체 폭발": "Vaal Detonate Dead",
    "바알 약탈": "Vaal Reave",
    "바알 얼음 폭발": "Vaal Ice Nova",
    "바알 얼음 화살": "Vaal Ice Shot",
    "바알 얼음의 부정함": "Vaal Impurity of Ice",
    "바알 연쇄 번개": "Vaal Arc",
    "바알 오브": "Vaal Orb",
    "바알 용암 방패": "Vaal Molten Shell",
    "바알 용암 타격": "Vaal Molten Strike",
    "바알 은총": "Vaal Grace",
    "바알 이중 타격": "Vaal Double Strike",
    "바알 전기불꽃": "Vaal Spark",
    "바알 점멸 타격": "Vaal Flicker Strike",
    "바알 정의의 화염": "Vaal Righteous Fire",
    "바알 지배": "Vaal Domination",
    "바알 지진": "Vaal Earthquake",
    "바알 질풍의 칼날": "Vaal Blade Flurry",
    "바알 징벌": "Vaal Smite",
    "바알 칼날 소용돌이": "Vaal Blade Vortex",
    "바알 폭풍 부름": "Vaal Storm Call",
    "바알 한기의 방어구": "Vaal Arctic Armour",
    "바알 한파": "Vaal Cold Snap",
    "바알 해골 소환": "Vaal Summon Skeletons",
    "바알 화산 균열": "Vaal Volcanic Fissure",
    "바알 화살비": "Vaal Rain of Arrows",
    "바알 화염 폭풍": "Vaal Firestorm",
    "바알 화염구": "Vaal Fireball",
    "바알 화염파": "Vaal Flameblast",
    "바알 환영 무기 투척": "Vaal Spectral Throw",
    "바알 황폐": "Vaal Blight",
    "바알 회복 토템": "Vaal Rejuvenation Totem",
    "바알 회오리바람": "Vaal Cyclone",
    "바알 회전베기": "Vaal Cleave",
    "바알의 그림자": "Shadow of the Vaal",
    "바주르": "Bazur",
    "반동의 독성 혼합물": "Poisonous Concoction of Bouncing",
    "반향의 머베일": "Merveil%2C the Reflection",
    "발굴": "Unearth",
    "발굴의 시체 소각": "Cremation of Exhuming",
    "발화의 화염 쇄도": "Flame Surge of Combusting",
    "방비의 돌 골렘 소환": "Summon Stone Golem of Safeguarding",
    "방출": "Discharge",
    "방치된 불길": "The Neglected Flame",
    "방패 돌진": "Shield Charge",
    "방패 타쇄": "Shield Crush",
    "방해 공작의 고드름 지뢰": "Icicle Mine of Sabotage",
    "방해 공작의 화산탄 지뢰": "Pyroclast Mine of Sabotage",
    "방혈": "Exsanguinate",
    "배신자 마책": "Marchak%2C The Betrayer",
    "번개 골렘 소환": "Summon Lightning Golem",
    "번개 덫": "Lightning Trap",
    "번개 도관": "Lightning Conduit",
    "번개 차원 이동": "Lightning Warp",
    "번개 첨탑 덫": "Lightning Spire Trap",
    "번개 타격": "Lightning Strike",
    "번개 화살": "Lightning Arrow",
    "번개의 순수함": "Purity of Lightning",
    "별빛 성배 철 플라스크": "Starlight Chalice",
    "병에 담긴 믿음 유황 플라스크": "Bottled Faith",
    "보라나의 준비 철 플라스크": "Voranas Preparation",
    "보조 젬": "Support Gems",
    "보호의 연결": "Protective Link",
    "복수의 함성": "Vengeful Cry",
    "복합 외상의 뼈 박살": "Boneshatter of Complex Trauma",
    "부서진 왕자": "The Broken Prince",
    "부식 유도자": "Enticer of Rot",
    "부식성 화살": "Caustic Arrow",
    "부족장의 방패 타쇄": "Shield Crush of the Chieftain",
    "부패 골렘 소환": "Summon Carrion Golem",
    "부패의 포식자 나르": "Gnar%2C Eater of Carrion",
    "부활자 톨먼": "Tolman%2C the Exhumer",
    "북극성의 용암 타격": "Molten Strike of the Zenith",
    "분광 분신의 거울 화살": "Mirror Arrow of Prismatic Clones",
    "분광 분신의 점멸 화살": "Blink Arrow of Prismatic Clones",
    "분노": "Anger",
    "분리의 공허 구체": "Void Sphere of Rending",
    "분사의 강철 관통": "Lancing Steel of Spraying",
    "분쇄자 렉타르": "Rektar%2C the Breaker",
    "분쇄자 베롯": "Berrots%2C The Breaker",
    "분쇄자 토룰": "Breaker Toruul",
    "분할 화살": "Split Arrow",
    "분할의 분할 화살": "Split Arrow of Splitting",
    "분할의 얼음 창": "Ice Spear of Splitting",
    "분해의 신성한 진노": "Divine Ire of Disintegration",
    "분해의 치직대는 창": "Crackling Lance of Disintegration",
    "불멸의 외침": "Immortal Call",
    "불사의 주인 카타리나": "Catarina%2C Master of Undeath",
    "불사조의 수호자": "Guardian of the Phoenix",
    "불안정의 서리 폭탄": "Frost Bomb of Instability",
    "불의 순수함": "Purity of Fire",
    "불타는 굴레": "Searing Bond",
    "불타는 마녀의 술 모조품 휘안석 플라스크": "Replica Witchfire Brew",
    "불타는 마녀의 술 휘안석 플라스크": "Witchfire Brew",
    "불타는 시신 필레아": "Pileah%2C Burning Corpse",
    "불타는 화살": "Burning Arrow",
    "불확실성의 칼날 폭풍": "Bladestorm of Uncertainty",
    "비명자 에이할": "Shrieker Eihal",
    "비전 헌신의 정의의 화염": "Righteous Fire of Arcane Devotion",
    "비전의 망토": "Arcane Cloak",
    "비참의 방출": "Discharge of Misery",
    "비취 플라스크": "Jade Flask",
    "빌로린 데몬테이머": "Wilorin Demontamer",
    "빙결의 여인": "Lady Stormflay",
    "빙타 광장 안뜰 지도": "The Vinktar Square",
    "빙타의 그릇 토파즈 플라스크": "Vessel of Vinktar",
    "빙하 망치": "Glacial Hammer",
    "빙하 방패 후려치기": "Glacial Shield Swipe",
    "빙하 폭포": "Glacial Cascade",
    "빛나는 묘약 루비 플라스크": "Coruscating Elixir",
    "빛에 휩싸임": "Wreathed in Light",
    "빛의 파멸 에레빅스": "Erebix%2C Lights Bane",
    "빠른 걸음": "Quickstep",
    "빠른 손의 레이프": "Leif%2C the Swift-Handed",
    "뼈 공물": "Bone Offering",
    "뼈 박살": "Boneshatter",
    "뼈의 요술사 부르톡": "Burtok%2C Conjurer of Bones",
    "사격 공세의 칼날비": "Bladefall of Volleys",
    "사나운 타격": "Wild Strike",
    "사람의 조롱 오와드": "Woad%2C Mockery of Man",
    "사술 폭발": "Hexblast",
    "사슬 갈고리": "Chain Hook",
    "사악함의 정수 흡수": "Essence Drain of Wickedness",
    "사자의 포효 화강암 플라스크": "Lions Roar",
    "사향의 "두 눈" 그렌": "Musky %22Two-Eyes%22 Grenn",
    "산 빚기": "Shaping the Mountains",
    "산산조각": "Sunder",
    "산산조각의 빙하 망치": "Glacial Hammer of Shattering",
    "산산조각의 얼음 골렘 소환": "Summon Ice Golem of Shattering",
    "산산조각의 환영 방패 투척": "Spectral Shield Throw of Shattering",
    "산성부리 오르비": "Orvi Acidbeak",
    "살육의 뼈 박살": "Boneshatter of Carnage",
    "살점 공물": "Flesh Offering",
    "살점 붙잡기": "Seize the Flesh",
    "상반의 사술폭발": "Hexblast of Contradiction",
    "상서로운 번개의 신성한 진노": "Divine Ire of Holy Lightning",
    "생명력": "Life",
    "샤브론의 악몽": "Nightmare of Shavronne",
    "서리 구체": "Frostbolt",
    "서리 구체의 얼음 폭발": "Ice Nova of Frostbolts",
    "서리 방벽": "Frost Wall",
    "서리 방패": "Frost Shield",
    "서리 칼날": "Frost Blades",
    "서리 폭탄": "Frost Bomb",
    "서리점멸": "Frostblink",
    "선대의 대전사": "Ancestral Warchief",
    "선대의 수호자": "Ancestral Protector",
    "선대의 함성": "Ancestral Cry",
    "설원에서의 춤": "Dance in the White",
    "섬뜩한 충전기": "Eldritch Battery",
    "성지 수호자": "Sanctum Guardian",
    "성지 집행자": "Sanctum Enforcer",
    "세계 빚기": "Shaping the World",
    "소각": "Incinerate",
    "소동의 회오리바람": "Cyclone of Tumult",
    "소실의 속죄의 낙인": "Penance Brand of Dissipation",
    "소용돌이": "Vortex",
    "소집": "Convocation",
    "소환의 종말의 낙인": "Armageddon Brand of Recall",
    "속죄의 낙인": "Penance Brand",
    "쇄도의 연쇄 번개": "Arc of Surging",
    "쇄도의 충격 화살": "Galvanic Arrow of Surging",
    "쇠약화": "Enfeeble",
    "수없이 조각난 존재": "He of Many Pieces",
    "수축의 화염파": "Flameblast of Contraction",
    "수호자 기동": "Animate Guardian",
    "수확 벽옥 절단기": "The Harvest",
    "수확자 소환": "Summon Reaper",
    "순간이동의 폭풍 연대": "Stormbind of Teleportation",
    "순수의 전령": "Herald of Purity",
    "술 취한 텔바르": "Telvar%2C the Inebriated",
    "쉐이퍼의 영역": "The Shapers Realm",
    "쉴 수 없는 그늘": "The Restless Shade",
    "스킬 젬": "Skill Gems",
    "시간의 균열": "Temporal Rift",
    "시간의 사슬": "Temporal Chains",
    "시신 점화자 필레아": "Pileah%2C Corpse Burner",
    "시체 불덩이": "Volatile Dead",
    "시체 소각": "Cremation",
    "시체 폭발": "Detonate Dead",
    "신념의 신성한 유물 소환": "Summon Holy Relic of Conviction",
    "신념의 파도": "Wave of Conviction",
    "신념파괴자 탈린": "Talin%2C Faithbreaker",
    "신비학자 낙인": "Arcanist Brand",
    "신성한 심판의 징벌": "Smite of Divine Judgement",
    "신성한 유물 소환": "Summon Holy Relic",
    "신성한 응징": "Divine Retribution",
    "신성한 진노": "Divine Ire",
    "신성한 화염 토템": "Holy Flame Totem",
    "신에게 선택받은 자": "Gods Chosen",
    "신의 슬픔 모조품 유황 플라스크": "Replica Sorrow of the Divine",
    "신의 슬픔 유황 플라스크": "The Sorrow of the Divine",
    "신체 전환": "Bodyswap",
    "신체의 껍질": "Somatic Shell",
    "실혈의 피부 찢기": "Lacerate of Haemorrhage",
    "쌍수 타격": "Dual Strike",
    "썩은 내장 수은 플라스크": "Rotgut",
    "씬의 부활 휘안석 플라스크": "Sins Rebirth",
    "아룬의 기둥 모조품 사구 지도": "Replica Pillars of Arun",
    "아룬의 기둥 사구 지도": "Pillars of Arun",
    "아우구스티나 솔라리아": "Augustina Solaria",
    "아틀라스의 세계": "Atlas of Worlds",
    "악몽의 징조": "Nightmares Omen",
    "악의": "Malevolence",
    "악취 나는 수도원 박물관 지도": "The Putrid Cloister",
    "암살자의 징표": "Assassins Mark",
    "앗지리의 금고실 바알 피라미드 지도": "Vaults of Atziri",
    "앗지리의 약속 자수정 플라스크": "Atziris Promise",
    "액턴의 악몽 무성한 성소 지도": "Actons Nightmare",
    "약탈": "Reave",
    "양손잡이의 쌍수 타격": "Dual Strike of Ambidexterity",
    "어둠의 서약": "Dark Pact",
    "얼어붙은 군단": "Frozen Legion",
    "얼음 골렘 소환": "Summon Ice Golem",
    "얼음 덫": "Ice Trap",
    "얼음 창": "Ice Spear",
    "얼음 충격": "Ice Crash",
    "얼음 폭발": "Ice Nova",
    "얼음 화살": "Ice Shot",
    "얼음의 순수함": "Purity of Ice",
    "얼음의 전령": "Herald of Ice",
    "엄습하는 서리": "Creeping Frost",
    "에너지 칼날": "Energy Blade",
    "에너지의 충격 화살": "Galvanic Arrow of Energy",
    "엑셀리스 오라픽스": "Excellis Aurafix",
    "여교장 브래타": "Headmistress Braeta",
    "여명의 현자 요리시": "Yorishi%2C Aurora-sage",
    "여사냥꾼의 화신": "Avatar of the Huntress",
    "역학 비": "Kinetic Rain",
    "역학 일제 사격": "Kinetic Fusillade",
    "역학 투사체": "Kinetic Bolt",
    "역학 폭발": "Kinetic Blast",
    "연금술사의 징표": "Alchemists Mark",
    "연금술의 오브": "Orb of Alchemy",
    "연막 지뢰": "Smoke Mine",
    "연발 사격": "Barrage",
    "연소 화재": "Conflagration",
    "연쇄 반응의 시체 폭발": "Detonate Dead of Chain Reaction",
    "연쇄 번개": "Arc",
    "열광": "Zealotry",
    "열상의 칼날 덫": "Blade Trap of Laceration",
    "영체 나선": "Spectral Helix",
    "영혼 거열기 석영 플라스크": "Soul Ripper",
    "영혼 공물": "Spirit Offering",
    "영혼 분리": "Soulrend",
    "영혼 포식자": "Eater of Souls",
    "영혼 포획자 석영 플라스크": "Soul Catcher",
    "영혼 희생의 금단의 의식": "Forbidden Rite of Soul Sacrifice",
    "영혼의 연결": "Soul Link",
    "예언의 정수 대형 하이브리드 플라스크": "Divination Distillate",
    "예언자의 포도주 황금 플라스크": "Wine of the Prophet",
    "예측 불허의 전기불꽃": "Spark of Unpredictability",
    "오라 그린게이트": "Orra Greengate",
    "오리아스의 미덕": "Oriaths Virtue",
    "오리아스의 복수": "Oriaths Vengeance",
    "오리아스의 종말 비스무트 플라스크": "Oriaths End",
    "오리아스의 철야": "Oriaths Vigil",
    "오바의 저주받은 전리품 지하 해양 지도": "Obas Cursed Trove",
    "오언 그레이퍼": "Eoin Greyfur",
    "올가미 화살": "Ensnaring Arrow",
    "올로스의 결의 철 플라스크": "Olroths Resolve",
    "올멕의 지성소 뼈 지하실 지도": "Olmecs Sanctum",
    "와카와 투아후 해안 지도": "Whakawairua Tuahu",
    "완력의 오크": "Oak the Mighty",
    "용암 방패": "Molten Shell",
    "용암 타격": "Molten Strike",
    "우루크 발레": "Uruk Baleh",
    "우유부단의 폭풍의 낙인": "Storm Brand of Indecision",
    "우트레드의 악몽": "Nightmare of Uhtred",
    "운율의 얼음 충격": "Ice Crash of Cadence",
    "울타리의 폭풍우": "Storm Rain of the Fence",
    "원거리 병기의 무기 기동": "Animate Weapon of Ranged Arms",
    "원격 기폭 장치 소환": "Summon Skitterbots",
    "원령의 수확자 소환": "Summon Reaper of Revenants",
    "원석의 올멕": "Olmec%2C the All Stone",
    "원소 약화": "Elemental Weakness",
    "원소의 순수함": "Purity of Elements",
    "원소의 일격": "Elemental Hit",
    "원시인": "The Primal One",
    "위상 질주": "Old Phase Run",
    "위축": "Wither",
    "위축의 황폐": "Blight of Atrophy",
    "위험의 재앙의 화살": "Scourge Arrow of Menace",
    "위협의 함성": "Intimidating Cry",
    "유리직공의 방울": "Glassblowers Bauble",
    "유성의 화염 골렘 소환": "Summon Flame Golem of the Meteor",
    "유성의 화염 폭풍": "Firestorm of Meteors",
    "유혈의 천공": "Perforate of Bloodshed",
    "육중대": "Massier",
    "육체와 돌": "Flesh and Stone",
    "은총": "Grace",
    "응징": "Punishment",
    "이그나 피닉스": "Igna Phoenix",
    "이중 타격": "Double Strike",
    "이중성의 천공": "Perforate of Duality",
    "인내의 축성의 진격": "Consecrated Path of Endurance",
    "인내의 함성": "Enduring Cry",
    "인화성": "Flammability",
    "일류 의사": "Master Surgeon",
    "일제 포격의 연발 사격": "Barrage of Volley Fire",
    "일촉즉발의 종말의 낙인": "Armageddon Brand of Volatility",
    "임박의 서리 폭탄": "Frost Bomb of Forthcoming",
    "자기 반사의 무기 기동": "Animate Weapon of Self Reflection",
    "자동 전력": "Autoexertion",
    "자동화": "Automation",
    "자부심": "Pride",
    "자연의 은혜": "Natures Boon",
    "작열 광선": "Scorching Ray",
    "잡종 과부": "Hybrid Widow",
    "장군의 함성": "Generals Cry",
    "장미": "Rose",
    "장작 부르기": "Call the Pyre",
    "재앙의 화살": "Scourge Arrow",
    "재의 딸 렐리 고야": "Leli Goya%2C Daughter of Ash",
    "재의 전령": "Herald of Ash",
    "재집결의 얼어붙은 군단": "Frozen Legion of Rallying",
    "잿더미 단지 은 플라스크": "Cinderswallow Urn",
    "잿빛 화살의 군자": "Lord of the Ashen Arrow",
    "저격": "Snipe",
    "저격수의 징표": "Snipers Mark",
    "저주받은 왕": "The Cursed King",
    "저주받은 자 클레이본 대장": "Captain Clayborne%2C The Accursed",
    "저항의 깃발": "Defiance Banner",
    "적출의 수확자 소환": "Summon Reaper of Eviscerating",
    "적혈구포식": "Erythrophagia",
    "전기 처형의 번개 화살": "Lightning Arrow of Electrocution",
    "전기불꽃": "Spark",
    "전기불꽃의 번개 덫": "Lightning Trap of Sparking",
    "전도성": "Conductivity",
    "전도성 격발": "Voltaxic Burst",
    "전도의 속죄의 낙인": "Penance Brand of Conduction",
    "전류의 번개 첨탑 덫": "Lightning Spire Trap of Zapping",
    "전송의 방혈": "Exsanguinate of Transmission",
    "전염": "Contagion",
    "전염성 일격": "Pestilent Strike",
    "전염의 황폐": "Blight of Contagion",
    "전이의 전염": "Contagion of Transference",
    "전쟁 깃발": "War Banner",
    "전쟁군주의 징표": "Warlords Mark",
    "전창조 자수정 플라스크": "Progenesis",
    "전투닭 돌부리": "Stonebeak%2C Battle Fowl",
    "전투마법사의 함성": "Battlemages Cry",
    "전향 덫": "Conversion Trap",
    "전호의 번개 타격": "Lightning Strike of Arcing",
    "절개의 질풍의 칼날": "Blade Flurry of Incision",
    "절단자 말리가로": "Maligaro the Mutilator",
    "절망": "Despair",
    "점멸 타격": "Flicker Strike",
    "점멸 화살": "Blink Arrow",
    "정밀함": "Precision",
    "정수 흡수": "Essence Drain",
    "정의의 시각": "Vision of Justice",
    "정의의 화염": "Righteous Fire",
    "정전기 타격": "Static Strike",
    "정전기의 구형 번개": "Ball Lightning of Static",
    "정화의 불길": "Purifying Flame",
    "제르피의 마지막 숨결 거대 마나 플라스크": "Zerphis Last Breath",
    "제물의 작열 광선": "Scorching Ray of Immolation",
    "제물의 지옥불 맹타": "Infernal Blow of Immolation",
    "제이네이 유수": "Jeinei Yuushu",
    "좀비 소환": "Raise Zombie",
    "종극의 겨울의 눈": "Eye of Winter of Finality",
    "종말의 낙인": "Armageddon Brand",
    "종말의 화신": "Avatar of Apocalypse",
    "주문투척": "Spellslinger",
    "주입된 교두보 선구자 지도": "Infused Beachhead",
    "죽어가는 해 루비 플라스크": "Dying Sun",
    "죽음과 의무 매장지 지도": "Death and Taxes",
    "죽지 않는 페어그레이브즈": "Fairgraves%2C Never Dying",
    "중첩의 호러": "Unravelling Horror",
    "증오": "Hatred",
    "증오의 맛 사파이어 플라스크": "Taste of Hate",
    "증폭의 지진": "Earthquake of Amplification",
    "지도": "Maps",
    "지도 마법 몬스터": "Map Magic Monsters",
    "지도 무리 규모": "Map Pack Size",
    "지도 희귀 몬스터": "Map Rare Monsters",
    "지도제작자의 끌": "Cartographers Chisel",
    "지동의 대지 강타": "Ground Slam of Earthshaking",
    "지뢰 폭발": "Detonate Mines",
    "지면 분쇄": "Earthshatter",
    "지배의 맹타": "Dominating Blow",
    "지속되는 칼날의 천상의 단도": "Ethereal Knives of Lingering Blades",
    "지식의 중재자": "The Arbiter of Knowledge",
    "지옥불 맹타": "Infernal Blow",
    "지옥불 함성": "Infernal Cry",
    "지저분한 포르텐티아": "Portentia%2C the Foul",
    "지진": "Earthquake",
    "지진 덫": "Seismic Trap",
    "지진 함성": "Seismic Cry",
    "지층 강타": "Tectonic Slam",
    "지혜의 참나무 비스무트 플라스크": "The Wise Oak",
    "직관의 연결": "Intuitive Link",
    "진노": "Wrath",
    "진창 생성자": "Maker of Mires",
    "진홍색 비 비나이아": "Binaia%2C Crimson Rain",
    "진홍색 시장 카다리스": "Kadaris%2C Crimson Mayor",
    "질주": "Dash",
    "질풍의 칼날": "Blade Flurry",
    "집결의 함성": "Rallying Cry",
    "징벌": "Smite",
    "징벌의 수호자 기동": "Animate Guardian of Smiting",
    "차가운 폭발의 서리점멸": "Frostblink of Wintry Blast",
    "착취 덫": "Siphoning Trap",
    "참수자의 아들 올로프": "Olof%2C Son of the Headsman",
    "천공": "Perforate",
    "천국의 번개 도관": "Lightning Conduit of the Heavens",
    "천둥의 전령": "Herald of Thunder",
    "천둥의 화신": "Avatar of Thunder",
    "천상의 단도": "Ethereal Knives",
    "청소부의 부패 골렘 소환": "Summon Carrion Golem of Scavenging",
    "청소부의 시체 폭발": "Detonate Dead of Scavenging",
    "초승달의 끝 세버트": "Sebbert%2C Crescents Point",
    "초자연적인 카리우스": "Carius%2C the Unnatural",
    "최고 권위자": "The Apex Assembly",
    "최상층 첨탑 포포로": "Poporo%2C the Highest Spire",
    "추락의 좀비 소환": "Raise Zombie of Falling",
    "축성의 진격": "Consecrated Path",
    "출중의 지면 분쇄": "Earthshatter of Prominence",
    "충격 폭발": "Shock Nova",
    "충격 화살": "Galvanic Arrow",
    "충격과 공포": "Shock and Horror",
    "충격의 역학 비": "Kinetic Rain of Impact",
    "충격장": "Galvanic Field",
    "충격파 토템": "Shockwave Totem",
    "충전 질주": "Charged Dash",
    "취약성": "Vulnerability",
    "치직대는 창": "Crackling Lance",
    "침식하는 자": "The Eroding One",
    "침하의 전염": "Contagion of Subsiding",
    "카루이의 피 축성된 생명력 플라스크": "Blood of the Karui",
    "카오스 골렘 소환": "Summon Chaos Golem",
    "카즈 아알라이": "Kaj Aalai",
    "카즈 야라즈": "Kaj Yaraaz",
    "카즈 쿠라": "Kaj Qura",
    "카타리나의 악몽": "Nightmare of Catarina",
    "칼날 덫": "Blade Trap",
    "칼날 선회": "Whirling Blades",
    "칼날 소용돌이": "Blade Vortex",
    "칼날 폭격": "Blade Blast",
    "칼날 폭풍": "Bladestorm",
    "칼날비": "Bladefall",
    "칼데루스": "Calderus",
    "캐어블레이드 늑대의 소굴 지하 강 지도": "Caer Blaidd%2C Wolfpacks Den",
    "코랄리토의 서명 다이아몬드 플라스크": "Coralitos Signature",
    "코브라 채찍": "Cobra Lash",
    "코텍스 결합된 지도": "Cortex",
    "코텍스 모조품 결합된 지도": "Replica Cortex",
    "큰독사의 맹독 타격": "Viper Strike of the Mamba",
    "키메라의 수호자": "Guardian of the Chimera",
    "키아라의 결의 은 플라스크": "Kiaras Determination",
    "타락한 삼위일체의 악몽": "Nightmare of the Depraved Trinity",
    "타락한 열병": "Corrupting Fever",
    "타쇄하는 주먹": "Crushing Fist",
    "탄약의 강철 분할": "Splitting Steel of Ammunition",
    "탄약의 강철 파편": "Shattering Steel of Ammunition",
    "태양부름 아샤": "Suncaller Asha",
    "태풍 파열 지뢰": "Stormblast Mine",
    "태풍의 눈": "Eye of the Storm",
    "터널함정": "Tunneltrap",
    "텅 빈 여인": "The Hollow Lady",
    "토르 오글로소": "Torr Olgosso",
    "퇴각의 서리 칼날": "Frost Blades of Katabasis",
    "투영의 소용돌이": "Vortex of Projection",
    "트라투스의 묵직한 타격": "Heavy Strike of Trarthus",
    "트라투스의 사슬 갈고리": "Chain Hook of Trarthus",
    "트라투스의 산산조각": "Sunder of Trarthus",
    "트라투스의 신념의 파도": "Wave of Conviction of Trarthus",
    "트라투스의 어둠의 서약": "Dark Pact of Trarthus",
    "트라투스의 영체 나선": "Spectral Helix of Trarthus",
    "트라투스의 칼날비": "Bladefall of Trarthus",
    "트라투스의 폭발 화살비": "Blast Rain of Trarthus",
    "트라투스의 폭풍 부름": "Storm Call of Trarthus",
    "트라투스의 환영 무기 투척": "Spectral Throw of Trarthus",
    "트라투스의 환영 방패 투척": "Spectral Shield Throw of Trarthus",
    "파괴 불가능한 존재의 악몽": "Nightmare of the Unbreakable",
    "파괴의 연결": "Destructive Link",
    "파괴의 폭발성 혼합물": "Explosive Concoction of Destruction",
    "파괴자 키타바": "Kitava%2C The Destroyer",
    "파멸": "Bane",
    "파생의 치직대는 창": "Crackling Lance of Branching",
    "파쇄의 역학 투사체": "Kinetic Bolt of Fragmentation",
    "파장의 원소의 일격": "Elemental Hit of the Spectrum",
    "파편의 폭발 덫": "Explosive Trap of Shrapnel",
    "패스파인더": "Pathfinder",
    "팽창의 지진 덫": "Seismic Trap of Swells",
    "퍼부음의 화염 폭풍": "Firestorm of Pelting",
    "퍼짐의 고드름 지뢰": "Icicle Mine of Fanning",
    "포격 분신의 거울 화살": "Mirror Arrow of Bombarding Clones",
    "포격 분신의 점멸 화살": "Blink Arrow of Bombarding Clones",
    "포대의 화살비": "Rain of Arrows of Artillery",
    "포식 토템": "Devouring Totem",
    "포자 폭발의 맹독성 비": "Toxic Rain of Sporeburst",
    "포탈": "Portal",
    "포화의 화살비": "Rain of Arrows of Saturation",
    "폭발 덫": "Explosive Trap",
    "폭발 화살": "Explosive Arrow",
    "폭발 화살비": "Blast Rain",
    "폭발성 혼합물": "Explosive Concoction",
    "폭발의 전기불꽃": "Spark of the Nova",
    "폭발의 화염 덫": "Fire Trap of Blasting",
    "폭풍 보주": "Orb of Storms",
    "폭풍 부름": "Storm Call",
    "폭풍 연대": "Stormbind",
    "폭풍 점사": "Storm Burst",
    "폭풍우": "Storm Rain",
    "폭풍의 낙인": "Storm Brand",
    "폭풍의 방패": "Tempest Shield",
    "폰디움의 사이렌 수사라": "Susara%2C Siren of Pondium",
    "푸어조이의 은신처 모조품 사원 지도": "Replica Poorjoys Asylum",
    "푸어조이의 은신처 사원 지도": "Poorjoys Asylum",
    "피 석화": "Petrified Blood",
    "피를 마시는 엘라빈": "ElAbin%2C Bloodeater",
    "피부 찢기": "Lacerate",
    "피와 모래": "Blood and Sand",
    "피의 격노": "Blood Rage",
    "피의 원류": "Blood Progenitor",
    "피의 인도자": "Bringer of Blood",
    "피폐의 장악": "Enervating Grasp",
    "피형성자 인바리": "Invari%2C The Bloodshaper",
    "필사의 정수 흡수": "Essence Drain of Desperation",
    "핏빛 사이렌": "The Sanguine Siren",
    "하늘 빚기": "Shaping the Skies",
    "하늘의 끝 조러스": "Jorus%2C Skys Edge",
    "하늘의 화신": "Avatar of the Skies",
    "하이세리아 여사": "Mistress Hyseria",
    "한기의 방어구": "Old Arctic Armour",
    "한파": "Cold Snap",
    "해골 소환": "Summon Skeletons",
    "해적 보물": "Pirate Treasure",
    "해적 영주 벨서": "Belcer%2C the Pirate Lord",
    "허약의 지면 분쇄": "Earthshatter of Fragility",
    "혼돈의 마엘스트롬 산호섬 지도": "Maelstr%C3%B6m of Chaos",
    "혼란의 사술폭발": "Hexblast of Havoc",
    "홍수의 마귀 오르무드": "Ormud%2C Fiend of the Flood",
    "화강암 플라스크": "Granite Flask",
    "화산 균열": "Volcanic Fissure",
    "화산의 시체 소각": "Cremation of the Volcano",
    "화산탄 지뢰": "Pyroclast Mine",
    "화살비": "Rain of Arrows",
    "화염 골렘 소환": "Summon Flame Golem",
    "화염 덫": "Fire Trap",
    "화염 벽": "Flame Wall",
    "화염 쇄도": "Flame Surge",
    "화염 질주": "Flame Dash",
    "화염 폭풍": "Firestorm",
    "화염구": "Fireball",
    "화염방사기 덫": "Flamethrower Trap",
    "화염의 숲": "Forest of Flames",
    "화염의 심장": "Heart of Flame",
    "화염의 연결": "Flame Link",
    "화염파": "Flameblast",
    "화폐": "Currency",
    "환기의 소각": "Incinerate of Venting",
    "환영 무기 투척": "Spectral Throw",
    "환영 방패 투척": "Spectral Shield Throw",
    "활력": "Vitality",
    "활력의 불타는 화살": "Burning Arrow of Vigour",
    "황폐": "Blight",
    "황혼의 사원 달의 사원 지도": "The Twilight Temple",
    "회복 토템": "Rejuvenation Totem",
    "회색 바람의 포효": "The Grey Wind Howls",
    "회색 역병": "The Grey Plague",
    "회색의 군주": "Lord of the Grey",
    "회오리": "Tornado",
    "회오리 사격": "Tornado Shot",
    "회오리바람": "Cyclone",
    "회전베기": "Cleave",
    "휩쓸기": "Sweep",
    "흡혈의 연결": "Vampiric Link",
    "희생의 신체 전환": "Bodyswap of Sacrifice",
    "히드라의 수호자": "Guardian of the Hydra",
    "힘의 벽": "Wall of Force",
    "힘의 부적": "Sigil of Power",
}
